databases:
  - name: receitas
    databaseName: receita
    user: hemer

services:
  - type: web
    name: receitas
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn alurareceita.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: receita
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4